### PR TITLE
Docker build action specifies `amd64` and `arm64` as `buildx` targets

### LINKED ISSUE #29: Pulling image via `docker pull ghcr.io/rmi-pacta/workflow.pacta:main` not working on `ARM64` architecture
I've been trying to test this repo out, and I am unable to pull the image from `ghcr.io` on `ARM64` architecture. Is that expected behavior?

Screenshot 2024-01-09 at 10 36 33

@AlexAxthelm maybe has info here? Maybe we need to specify the platform in the build actions here: https://github.com/RMI-PACTA/workflow.pacta/tree/main/.github/workflows

### PR DESCRIPTION
**Pull request by jdhoffa**
Maybe closes #29

### CODE REVIEW

**Comment by jdhoffa** [comment]
White-space commit seems to be artifact of making this change as a GitHub patch.

I didn't test this locally, figured the best way is to see if the .github actions run successfully and test the image from the `ghcr` image. Will ping back here after tested.

**Comment by jdhoffa** [comment]
Workflow build is failing because I do not have the authorization to push to the container registry for this repository. 
@AlexAxthelm or @cjyetman can you add me as a collaborator to this repo please?

**Comment by cjyetman** [comment]
> Workflow build is failing because I do not have the authorization to push to the container registry for this repository. @AlexAxthelm or @cjyetman can you add me as a collaborator to this repo please?

done!

**Comment by cjyetman** [comment]
@jdhoffa you might have to open a new PR... re-triggering after making you an admin still failed with the same message

**Comment by cjyetman** [comment]
@jdhoffa or/actually, you may have to create a PR branch in this repo rather than making a PR from a fork

**Comment by jdhoffa** [comment]
Closing in favour of #31

**Pull request closed without merging**
