### PR TITLE
Update build-and-push-Docker-image.yml

### PR DESCRIPTION
**Pull request by cjyetman**

### CODE REVIEW

**Comment by jdhoffa** [comment]
Hmm doesn't appear to solve the problem...
https://github.com/RMI-PACTA/workflow.pacta/pkgs/container/workflow.pacta/165235322?tag=pr31

**Comment by cjyetman** [comment]
I think I got closer with...
https://github.com/RMI-PACTA/workflow.pacta/blob/87b5aa96da31057c96e5852c1abfc5ae991a5ccf/.github/workflows/build-and-push-Docker-image.yml#L55-L63

but now it fails to install {pak} in the arm64 build, probably because the CRAN repo is targeting https://packagemanager.posit.co/cran/__linux__/jammy/2023-10-30
https://github.com/RMI-PACTA/workflow.pacta/actions/runs/7465370294/job/20314558081?pr=31#step:6:654
https://github.com/RMI-PACTA/workflow.pacta/blob/53fab3f82d4b203911826f7fd4b6fad394a5f64e/Dockerfile#L43

We could maybe try a more generic RSPM repo URL

**Comment by cjyetman** [comment]
It seems to be working now, but it's verrrry slow.

I had to
- install QEMU with `docker/setup-qemu-action@v3` so Docker can emulate a different architecture
- tell `docker/setup-buildx-action@v3` to setup with `platforms: linux/amd64,linux/arm64`
- tell `docker/build-push-action@v5` to build with `platforms: linux/amd64,linux/arm64`
- use the generic RSPM repo URL `https://packagemanager.posit.co/cran/2023-10-30` so it doesn't try to install binaries built for Jammy/amd64 when building the arm64 version
- install {pak} from r-lib's repo which contains pre-compiled binaries for both linux/amd64 and linux/arm64

Whether it will successfully push and tag both versions to GHCR is yet to be seen. Build is at +40min and will fail at 45min. Might have to bump the timeout even further. Not sure if the speed will improve once one version has successfully completed and some stuff gets cached.

**Comment by cjyetman** [comment]
arm64 builds now and pushes to GHCR. You can test it with something like...

``` shell
tag_name=pr31
image_name=ghcr.io/rmi-pacta/workflow.pacta:$tag_name
data_dir=~/github/pactaverse/pacta-data
input_dir=./input_dir
output_dir=./output_dir

docker run -it --rm \
  --network none \
  --pull=always \
  --platform linux/arm64 \
  --mount type=bind,readonly,source=${data_dir},target=/pacta-data \
  --mount type=bind,source=${output_dir},target=/output_dir \
  --mount type=bind,source=${input_dir},target=/input_dir \
  $image_name
```

**Comment by jdhoffa** [comment]
Is it taking so long because we are not specifying the pre-built CRAN repositories now? 
ie. we are trying to do BOTH `ARM64` and `AMD64`, so we can't pick a specific libraries and has to build everything from scratch?
Is this worth it, just to support multiple architectures? What is the use-case of that even? Can we just revert to specifying the architecture like we did before? 

Seems like there are cons to this updated build process, and no (immediate) pros... but maybe I am missing something

**Comment by cjyetman** [comment]
Yeah, nobody that I know of builds Linux arm64 binaries (yet). The amd64 builds in less than 10 minutes.

**Comment by cjyetman** [comment]
But also... compiling those binaries in emulation is what's painfully slow. We could maybe setup a matrix so the arm64 builds on an arm64 vm.

**Comment by cjyetman** [comment]
> What is the use-case of that even? 

The benefit would be automatically built images that run significantly faster on arm64 (which includes every MacBook sold in the past ~3 years). At the moment, I could certainly live without it because Docker's emulation for running instances/containers on macOS has improved quite a bit over the past couple years, so the amd64 build runs pretty smooth for me.

**Comment by cjyetman** [comment]
> we are trying to do BOTH `ARM64` and `AMD64`, so we can't pick a specific libraries and has to build everything from scratch?

To be clear, my impression is that using the generic RSPM URL does **not** prevent the amd64 from installing binaries, so that process is pretty quick... there just aren't any linux/arm64 binaries to be had, so the arm64 build is what takes forever.

**Comment by jdhoffa** [comment]
> > What is the use-case of that even?
> 
> The benefit would be automatically built images that run significantly faster on arm64 (which includes every MacBook sold in the past ~3 years). At the moment, I could certainly live without it because Docker's emulation for running instances/containers on macOS has improved quite a bit over the past couple years, so the amd64 build runs pretty smooth for me.

But, our images used to build/ work fine on `ARM64` before I left? I was able to pull and run everything. It is only now that I am getting this problem: https://github.com/RMI-PACTA/workflow.pacta/issues/29

**Comment by cjyetman** [comment]
> But, our images used to build/ work fine on `ARM64` before I left? I was able to pull and run everything. It is only now that I am getting this problem: #29

see my response in #29 

I think what we've learned here is that building an arm64 version simultaneously while building an amd64 version is technically possible, but not worth the extra time it takes. I will close this PR, maybe keep the branch around, and open an issue to remind us to check if the situation has improved (e.g. someone is providing pre-built arm64 binaries) sometime in the future.

**Pull request closed without merging**
