### PR TITLE
Feature/sysdep check

### LINKED ISSUE #17: Add workflow to check that system deps are installed
I was surprised to find that `pandoc` is on the list of sys deps for the image defined in Dockerfile (for now), but when setting the `pkg.sysreqs` R option to `FALSE`, `pak` didn't throw any errors (just messages) on installation of `rmarkdown` (as binary, not from source).

`sysreqs_check_installed` is able to identify any missing sysreqs, and we should probably be running it as a check after we install any packages.

https://pak.r-lib.org/reference/sysreqs_check_installed.html

Possibly as a step in the build-and-push workflow with: https://docs.docker.com/build/ci/github-actions/test-before-push/

### PR DESCRIPTION
**Pull request by AlexAxthelm**
Creates a workflow to check if `pak` recognizes the system dependencies, and calls it as part of the build workflow.

resolves #17

### CODE REVIEW

**Comment by cjyetman** [comment]
To be honest, I think this is unnecessary, and given that `pak::sysreqs_check_installed` checks all installed packages, I would guess this is more likely to throw an error about something that we don't really care about versus a problem with one of the few packages we actually do care about. If this just drops a warning somewhere, than I guess it's harmless enough, but if this blocks builds from completing I'd rather do without.

**Comment by AlexAxthelm** [comment]
> `pak::sysreqs_check_installed` checks all installed packages

But other than what's showing up in the `rocker` base image, we're only installing our packages and their necessary dependencies.

**Comment by cjyetman** [comment]
> > `pak::sysreqs_check_installed` checks all installed packages
> 
> But other than what's showing up in the `rocker` base image, we're only installing our packages and their necessary dependencies.

I certainly hope so LOL.... but `pak::sysreqs_check_installed` doesn't know what packages we installed or Rocker installed, so it will just check everything.

**Comment by AlexAxthelm** [comment]
> so it will just check everything.

Yeah, but for our purposes, I think that's what we want. If we find this throws a lot of useless errors, I'm fine with dropping it.

**Review by cjyetman — APPROVED** [review]

**Pull request merged**
